apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currency-exporter-dev
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/shaposhnikoff/argo_helm_k8s_test_task.git'
    path: helm/currency-exporter
    targetRevision: HEAD
    helm:
      values: |-
        image:
          repository: shaposhnikoff/currency-exporter
          tag: aef662b
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus-operator
        serviceAccount:
          create: true
          name:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::1234512345:role/data-dev-data-serviceaccount"
            eks.amazonaws.com/sts-regional-endpoints: "true"
        extraEnv:
          - name: INTERVAL_MINUTES
            value: "60"
          - name: PROMETHEUS_ADDRESS
            value: "0.0.0.0"
          - name: PROMETHEUS_PORT
            value: "9112"
          - name: EMR_ROLE_ARN
            value: "arn:aws:iam::1234512345:role/data-dev-ec2"
          - name: DRAIF_ROLE_ARN
            value: "arn:aws:iam::1234512345:role/data-dev-ec2"
