name: Docker Image CI

on:
  push:
    paths:
    - 'src/currency/**'
  pull_request:
    paths: 
    - 'src/currency/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push
      if: always()
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src/currency
        push: false
        tags: shaposhnikoff/dmrgateway:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
