name: Docker Image CI

on:
  push:
    paths:
    - 'src/currency/**'
  pull_request:
    paths: 
    - 'src/currency/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      if: always()
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./src/currency
        push: true
        tags: shaposhnikoff/currency-exporter:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
