name: Docker Image CI

on:
  push:
    paths:
    - 'src/currency/**'
  pull_request:
    paths: 
    - 'src/currency/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}


    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        IMAGE="shaposhnikoff/currency-exporter"
        echo ::set-output name=tagged_image::${IMAGE}:${TAG}
        echo ::set-output name=tag::${TAG}


    - name: Build and push
      if: always()
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./src/currency
        push: true
        tags: ${{ steps.prep.outputs.tagged_image }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Image tag
      run: echo ${{ steps.prep.outputs.tag }}

    - name: Setup yq
      run: | 
        wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O yq
        chmod +x yq

    - name: Update helm values file with tag version
      run: | 
         ./yq -i '.image.tag="${{ steps.prep.outputs.tag }}"' helm/currency-exporter/values.yaml

    - name: Update ARGO App values file with tag version
      run: | 
         ./yq e -i '.spec.source.helm.values |= (from_yaml | .image.tag = "${{ steps.prep.outputs.tag }}" | to_yaml)' argo_apps/dev_app.yaml


    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag to ${{ steps.prep.outputs.tag }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}




