on:
  push:
    branches: [ main1 ]
  pull_request:
    branches: [ main1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Use Node.js
         uses: actions/setup-node@v1
         with:
          node-version: '12.x'
       - run: npm install
       - run: npm run
       - run: npm test
      
       - name: Check Out Repo 
         uses: actions/checkout@v2
       - name: Login to Docker Hub
         env:
           DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
           DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
         run: | 
            docker login -u $DOCKER_USER -p $DOCKER_PASS
       - name: Set up Docker Buildx
         run: | 
            docker build .
             
       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: ./
           file: ./Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/yourimagename:yourtag
           
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
